[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "100%"
#tracing_enabled = true

[log]
level = "debug"
mode = "console"

[http]
enabled_services = ["appregistrysvc", "ocdavsvc", "datasvc","preferencessvc", "prometheussvc"]
enabled_middlewares = ["cors", "auth"]
network = "tcp"
address = "0.0.0.0:9998"

[http.middlewares.auth]
gatewaysvc = "0.0.0.0:9999"
credential_strategy = "basic"
token_strategy = "header"
token_writer = "header"
token_manager = "jwt"
skip_methods = ["/owncloud/status.php", "/metrics"]

[http.middlewares.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http.services.appregistrysvc]
prefix = "appregistry"
gatewaysvc = "localhost:9999"

[http.services.preferencessvc]
prefix = "preferences"
gatewaysvc = "localhost:9999"

[http.services.iframeuisvc]
prefix = "iframe"

[http.services.webuisvc]
prefix = "ui"

[http.services.ocdavsvc]
prefix = "owncloud"
chunk_folder = "/var/tmp/revad/chunks"
gatewaysvc = "localhost:9999"
enable_cors = true

[http.services.datasvc]
driver = "eos"
prefix = "data"
temp_folder = "/var/tmp/"

[http.services.datasvc.drivers.eos]
master_url = "eosuser-internal.cern.ch"
namespace = "/eos/test/labradorsvc"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
enabled_services = ["storageprovidersvc", "authsvc", "storageregistrysvc", "appregistrysvc", "appprovidersvc", "preferencessvc", "usershareprovidersvc"]
enabled_interceptors = ["auth"]

[grpc.services.usershareprovidersvc]
driver = "memory"

[grpc.services.storageprovidersvc]
driver = "eos"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://localhost:9998/data"

[grpc.services.storageprovidersvc.available_checksums]
md5   = 100
unset = 1000

[grpc.services.storageprovidersvc.drivers.eos]
master_url = "eosuser-internal.cern.ch"
namespace = "/eos/test/labradorsvc/"

[grpc.services.authsvc]
auth_manager = "json"
token_manager = "jwt"
user_manager = "json"

[grpc.services.authsvc.auth_managers.json]
users =  "cmd/revad/users.json"

[grpc.services.authsvc.user_managers.json]
users =  "cmd/revad/users.json"

[grpc.services.authsvc.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.storageregistrysvc]
driver = "static"

[grpc.services.storageregistrysvc.drivers.static.rules]
"/" = "localhost:9999"
"123e4567-e89b-12d3-a456-426655440000" = "localhost:9999"

[grpc.services.appregistrysvc]
driver = "static"

[grpc.services.appregistrysvc.static.rules]
".txt" = "localhost:9999"
"text/plain" = "localhost:9999"

[grpc.services.appprovidersvc]
driver = "demo"

[grpc.services.appprovidersvc.demo]
iframe_ui_provider = "http://localhost:9998/iframeuisvc"

[grpc.interceptors.auth]
token_manager = "jwt"
skip_methods = ["/cs3.authv0alpha.AuthService/GenerateAccessToken", "/cs3.authv0alpha.AuthService/WhoAmI"]

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"
