language: go

go:
  - 1.11.x

before_install:
  - go get -u golang.org/x/lint/golint

script:
  - golint -set_exit_status ./... # enfoce std style-guide
  - env GO111MODULE=on go build -v ./...
  - go vet ./... # enforce best practices
  - env GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
