language: go

go:
  - 1.11.x

before_install:
  - env GO111MODULE=on go build -v ./...

script:
  - golint -set_exit_status ./... # enfoce  style-guide
  - env GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
