[shared]
jwt_secret = "Pive-Fumkiu4"
gatewaysvc = "localhost:19000"

[grpc]
address = "0.0.0.0:19000"

[grpc.services.gateway]
commit_share_to_storage_grant = false
datagateway = "http://localhost:19001/data"
transfer_shared_secret = "replace-me-with-a-transfer-secret" # for direct uploads
transfer_expires = 6 # give it a moment

[grpc.services.authregistry]
driver = "static"

[grpc.services.usershareprovider]
driver = "json"

[grpc.services.usershareprovider.json]
file = /var/tmp/reva/usershares.json

[grpc.services.ocmcore]

[grpc.services.ocminvitemanager]
driver = "json"

[grpc.services.ocmshareprovider]
driver = "json"

[grpc.services.ocmshareprovider.drivers.json]
file = "/var/tmp/reva/shares_server_1.json"

[grpc.services.ocmproviderauthorizer]
driver = "json"

[grpc.services.ocmproviderauthorizer.drivers.json]
providers = "providers.demo.json"

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.storageprovider]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
expose_data_server = true
data_server_url = "http://localhost:19001/data"
enable_home_creation = true

[http]
enabled_services = ["ocmd"]
enabled_middlewares = ["providerauthorizer", "cors"]
address = "0.0.0.0:19001"

[http.services.dataprovider]
driver = "local"
temp_folder = "/var/tmp/"

[http.services.dataprovider.drivers.local]
namespace = "/var/tmp/reva/"
user_layout = "{{.Username}}"
enable_home = true

[http.services.ocmd]
prefix = "ocm"

[http.middlewares.providerauthorizer]
driver = "json"

[http.middlewares.providerauthorizer.drivers.json]
providers = "providers.demo.json"

[http.services.ocs]
prefix = "ocs"

[http.middlewares.cors]
