[http]
address = "0.0.0.0:9600"

# Security settings
[http.services.siteacc.security]
creds_passphrase = "superdupersecret"

# Connection to the GOCDB
[http.services.siteacc.gocdb]
url = "https://sciencemesh-test.uni-muenster.de/gocdb/"
write_url = "https://sciencemesh-test.uni-muenster.de/gocdbpi/"
apikey = "verysecret"

# Set up the storage driver
[http.services.siteacc.storage]
driver = "file"
[http.services.siteacc.storage.file]
operators_file = "/var/revad/operators.json"
accounts_file = "/var/revad/accounts.json"

# Email related settings
[http.services.siteacc.email]
notifications_mail = "science.mesh@example.com"

# The SMTP server used for sending emails
[http.services.siteacc.email.smtp]
sender_mail = "science.mesh@example.com"
smtp_server = "mail.example.com"
smtp_port = 25
disable_auth = true

# The webserver section defines various webserver-related settings
[http.services.siteacc.webserver]
url = "https://sciencemesh-test.uni-muenster.de/api/accounts/"
session_timeout = 60
