[log]
level = "trace"

[shared]
gatewaysvc = "your.revad.com:19000"

[grpc]
address = "0.0.0.0:19001"

[grpc.services.storageprovider]
driver = "ocmoutcoming"
mount_path = "/ocm"
mount_id = "ocm"
expose_data_server = true
data_server_url = "https://your.revad.com:4430/data"

[grpc.services.storageprovider.drivers.ocmoutcoming]
machine_secret = "machine-api-key"

[grpc.services.authprovider]
auth_manager = "ocmshares"

[http]
address = "0.0.0.0:4430"
certfile = "/etc/revad/tls/your.revad.ssl.crt"
keyfile = "/etc/revad/tls/your.revad.ssl.key"

[http.services.dataprovider]
driver = "ocmoutcoming"

[http.services.dataprovider.drivers.ocmoutcoming]
machine_secret = "machine-api-key"
