[log]
level = "trace"

[shared]
gatewaysvc = "0.0.0.0:19000"

[grpc]
address = "your.revad.com:19030"

[grpc.services.authprovider]
auth_manager = "machine"

[grpc.services.authprovider.auth_managers.machine]
api_key = "machine-api-key"
gateway_addr = "your.revad.com:19000"
