[shared]
jwt_secret = "Pive-Fumkiu4"
gatewaysvc = "localhost:19000"

# This gateway.toml config file will start a reva service that:
# - serves as a gateway for all requests
# - looks up the storageprovider using a storageregistry
# - looks up the authprovider using an authregistry
# - serves the gateway on grpc port 19000
# - serves http datagateway on port 19001
#   - /data - datagateway: file up and download
[grpc]
address = "0.0.0.0:19000"

[grpc.services.gateway]
# registries
authregistrysvc = "localhost:19000"
storageregistrysvc = "localhost:19000"
# user metadata
preferencessvc = "localhost:18000"
userprovidersvc = "localhost:18000"
# an approvider lives on "localhost:18000" as well, see users.toml
# sharing
usershareprovidersvc = "localhost:17000"
publicshareprovidersvc = "localhost:17000"
# ocm
ocmcoresvc = "localhost:13000"
ocmshareprovidersvc = "localhost:13000"
ocminvitemanagersvc = "localhost:13000"
ocmproviderauthorizersvc = "localhost:13000"
# other
commit_share_to_storage_grant = true
datagateway = "http://localhost:19001/data"
transfer_shared_secret = "replace-me-with-a-transfer-secret" # for direct uploads
transfer_expires = 6 # give it a moment
#disable_home_creation_on_login = true

[grpc.services.authregistry]
driver = "static"

[grpc.services.authregistry.drivers.static.rules]
basic = "localhost:18000" # started with the users.toml
bearer = "localhost:20099" # started with the frontend.toml

[grpc.services.storageregistry]
driver = "static"

[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]

# mount a home storage provider that uses a context based path wrapper
# to jail users into their home dir
"/home" = {"address" = "localhost:12000"}

# mount a storage provider without a path wrapper for direct access to users.
"/oc" = {"address" = "localhost:11000"}
"123e4567-e89b-12d3-a456-426655440000" = {"address" = "localhost:11000"}
# another mount point might be "/projects/"

[http]
address = "0.0.0.0:19001"

[http.services.datagateway]
transfer_shared_secret = "replace-me-with-a-transfer-secret"
