[shared]
jwt_secret = "Ment1x-T0pS3cr3t"

[http]
address = "0.0.0.0:9600"
enabled_services = ["mentix"]

[http.services.mentix]
update_interval = "15m"

[http.services.mentix.connectors.gocdb]
address = "http://sciencemesh-test.uni-muenster.de"

# Sites can also be stored in a local file
[http.services.mentix.connectors.localfile]
file = "/usr/share/revad/sites.json"

# Enable the WebAPI exporter
[http.services.mentix.exporters.webapi]
endpoint = "/"

# Enable the CS3API and Site Locations exporters
[http.services.mentix.exporters.cs3api]
[http.services.mentix.exporters.siteloc]
# If this setting is omitted, all connectors will be used as data sources
enabled_connectors = ["gocdb"]

# Configure the Prometheus Service Discovery:
# [http.services.mentix.exporters.promsd]
# The following files must be made available to Prometheus.
# They can then be used as the file_sd source of a job.
# metrics_output_file = "/usr/share/prom/sciencemesh_metrics.json"
# blackbox_output_file = "/usr/share/prom/sciencemesh_blackbox.json"
