[shared]
insecure = true

[http]
address = "0.0.0.0:9600"

[http.services.mentix]
update_interval = "15m"

[http.services.mentix.connectors.gocdb]
address = "http://sciencemesh-test.uni-muenster.de"
apikey = "abc123"

# Configure the service types that are considered as critical/essential
[http.services.mentix.services]
critical_types = ["REVAD"]

# Enable the WebAPI exporter
[http.services.mentix.exporters.webapi]
endpoint = "/"

# Enable the CS3API and Site Locations exporters
[http.services.mentix.exporters.cs3api]
[http.services.mentix.exporters.siteloc]
# If this setting is omitted, all connectors will be used as data sources
enabled_connectors = ["gocdb"]
# Enable the Metrics exporter
[http.services.mentix.exporters.metrics]

# Set up the accounts service used to query information about accounts associated with registered sites
[http.services.mentix.accounts]
# Depending on where the service is running, localhost may also be used here
url = "https://sciencemesh.example.com/iop/accounts"
user = "username"
password = "userpass"

# Configure the Prometheus Service Discovery:
[http.services.mentix.exporters.promsd]
# The following path must be made available to Prometheus.
# The contained target files can then be used as the file_sd sources of a job.
output_path = "/usr/share/prom"
