[shared]
jwt_secret = "Pive-Fumkiu4"
gatewaysvc = "localhost:17000"

[grpc]
address = "0.0.0.0:17000"

[grpc.services.gateway]
authregistrysvc = "localhost:17000"
storageregistrysvc = "localhost:17000"
preferencessvc = "localhost:17000"
userprovidersvc = "localhost:17000"
usershareprovidersvc = "localhost:17000"
publicshareprovidersvc = "localhost:17000"
ocmcoresvc = "localhost:17000"
ocmshareprovidersvc = "localhost:17000"
ocminvitemanagersvc = "localhost:17000"
ocmproviderauthorizersvc = "localhost:17000"
commit_share_to_storage_grant = false
datagateway = "http://localhost:17001/data"
transfer_shared_secret = "replace-me-with-a-transfer-secret" # for direct uploads
transfer_expires = 6 # give it a moment

[grpc.services.authregistry]
driver = "static"

[grpc.services.authregistry.drivers.static.rules]
basic = "localhost:17000"

[grpc.services.storageregistry]
driver = "static"

[grpc.services.storageregistry.drivers.static]
home_provider = "/"

[grpc.services.storageregistry.drivers.static.rules]
"/" = "localhost:17000"
"123e4567-e89b-12d3-a456-426655440000" = "localhost:17000"

[grpc.services.usershareprovider]
driver = "memory"

[grpc.services.ocmcore]
driver = "json"

# Note that ocmcore and ocmshareprovider should use the same file for storing the shares.
[grpc.services.ocmcore.drivers.json]
file = "/var/tmp/reva/shares_server_2.json"

[grpc.services.ocminvitemanager]
driver = "json"

[grpc.services.ocmshareprovider]
driver = "json"

[grpc.services.ocmshareprovider.drivers.json]
file = "/var/tmp/reva/shares_server_2.json"

[grpc.services.ocmproviderauthorizer]
driver = "json"

[grpc.services.ocmproviderauthorizer.drivers.json]
providers = "providers.demo.json"

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.storageprovider]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
expose_data_server = true
data_server_url = "http://localhost:17001/data"
enable_home_creation = true

[grpc.services.storageprovider.drivers.local]
namespace = "/var/tmp/reva/"
user_layout = "{{.Username}}"
enable_home = true

[grpc.services.authprovider]
auth_manager = "json"

[grpc.services.authprovider.auth_managers.json]
users = "users.demo.json"

[grpc.services.userprovider]
driver = "json"

[grpc.services.userprovider.drivers.json]
users = "users.demo.json"

[http]
enabled_services = ["ocmd"]
enabled_middlewares = ["providerauthorizer", "cors"]
address = "0.0.0.0:17001"

[http.services.dataprovider]
driver = "local"
temp_folder = "/var/tmp/"

[http.services.dataprovider.drivers.local]
namespace = "/var/tmp/reva/"
user_layout = "{{.Username}}"
enable_home = true

[http.services.ocmd]
prefix = "ocm"

[http.middlewares.providerauthorizer]
driver = "json"

[http.middlewares.providerauthorizer.drivers.json]
providers = "providers.demo.json"

[http.services.ocs]
prefix = "ocs"

[http.middlewares.cors]
